name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]    
    types: [opened, synchronize]
env:
  SKIP: ${{ contains(join(github.event.commits.*.message, ', '), '#skip' ) }}
jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style        
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Test Failure
        env:
          COMMIT_LINKS: ${{ join(github.event.commits.*.url, ', ')}}
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
            severity: error
            details: Build failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  e2e-test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [checks, e2e-test]
    if: ${{ needs.checks.result == 'success' && needs.e2e-test.result == 'success' && github.event_name == 'push' && github.env.SKIP == 'false'}}
    steps:
    - name: commit messages
      run: echo "env.SKIP"
    - name: Trigger deployment
      run: curl https://api.render.com/deploy/srv-${{ secrets.SRV_ID }}?key=${{ secrets.API_KEY }}
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ success() }}
      with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && github.env.SKIP == 'false'}}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: commit messages
      run: echo "env.SKIP"
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  a_test_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          SKIP: ${{ contains(join(github.event.commits.*.message, ', '), '#skip' ) }}
        run: echo "$SKIP"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.url) }}
        run: echo "$COMMIT_MESSAGES"
